// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateFileInput struct {
	Name     string `json:"name"`
	Location string `json:"location"`
}

type CreateMechanicalPressInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type CreateRawMaterialInput struct {
	Code   string `json:"code"`
	Name   string `json:"name"`
	Number int    `json:"number"`
}

type CreateRoleInput struct {
	Name string `json:"name"`
}

type CreateStandardPartInput struct {
	Code   string `json:"code"`
	Name   string `json:"name"`
	Number int    `json:"number"`
}

type CreateToolInput struct {
	Code                 string  `json:"code"`
	Name                 string  `json:"name"`
	CreationDate         *string `json:"creationDate,omitempty"`
	Dimensions           *string `json:"dimensions,omitempty"`
	Note                 *string `json:"note,omitempty"`
	ToolStroke           *string `json:"toolStroke,omitempty"`
	WorkpieceDescription *string `json:"workpieceDescription,omitempty"`
	ToolType             *uint   `json:"toolType,omitempty"`
	ToolAssociation      *uint   `json:"toolAssociation,omitempty"`
}

type CreateToolRepairRecordInput struct {
	DateStarted            *time.Time `json:"dateStarted,omitempty"`
	DateEnded              *time.Time `json:"dateEnded,omitempty"`
	RepairDescription      *string    `json:"repairDescription,omitempty"`
	MalfunctionDescription *string    `json:"malfunctionDescription,omitempty"`
	DeadlineDate           *time.Time `json:"deadlineDate,omitempty"`
	Material               *string    `json:"material,omitempty"`
	TimeSpent              *string    `json:"timeSpent,omitempty"`
	ExternalServices       *string    `json:"externalServices,omitempty"`
	Note                   *string    `json:"note,omitempty"`
	User                   *uint      `json:"user,omitempty"`
}

type CreateToolTypeInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type CreateUserInput struct {
	UserName  *string `json:"userName,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Password  *string `json:"password,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UpdateMechanicalPressInput struct {
	ID   int    `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type UpdateRawMaterialInput struct {
	ID     int    `json:"id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
	Number int    `json:"number"`
}

type UpdateStandardPartInput struct {
	ID     int    `json:"id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
	Number int    `json:"number"`
}

type UpdateToolTypeInput struct {
	ID   int    `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}
