package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/Svarcf/sever_go/internal/graph/model"
	"github.com/Svarcf/sever_go/internal/models"
)

// CreateFile is the resolver for the createFile field.
func (r *mutationResolver) CreateFile(ctx context.Context, createFileInput *model.CreateFileInput) (*models.FileDTO, error) {
	file := models.NewFile(createFileInput.Name, createFileInput.Location)
	return r.FileService.CreateFile(file)
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context) ([]*models.FileDTO, error) {
	return r.FileService.GetFiles()
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, id uint) (*models.FileDTO, error) {
	return r.FileService.GetFileById(id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
