package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"fmt"

	"github.com/Svarcf/sever_go/internal/graph/model"
	"github.com/Svarcf/sever_go/internal/models"
)

// CreateMechanicalPress is the resolver for the createMechanicalPress field.
func (r *mutationResolver) CreateMechanicalPress(ctx context.Context, createMechanicalPressInput *model.CreateMechanicalPressInput) (*models.MechanicalPress, error) {
	panic(fmt.Errorf("not implemented: CreateMechanicalPress - createMechanicalPress"))
}

// UpdateMechanicalPress is the resolver for the updateMechanicalPress field.
func (r *mutationResolver) UpdateMechanicalPress(ctx context.Context, updateMechanicalPressInput *model.UpdateMechanicalPressInput) (*models.MechanicalPress, error) {
	panic(fmt.Errorf("not implemented: UpdateMechanicalPress - updateMechanicalPress"))
}

// MechanicalPresses is the resolver for the mechanicalPresses field.
func (r *queryResolver) MechanicalPresses(ctx context.Context) ([]*models.MechanicalPress, error) {
	panic(fmt.Errorf("not implemented: MechanicalPresses - mechanicalPresses"))
}

// MechanicalPress is the resolver for the mechanicalPress field.
func (r *queryResolver) MechanicalPress(ctx context.Context, id uint) (*models.MechanicalPress, error) {
	panic(fmt.Errorf("not implemented: MechanicalPress - mechanicalPress"))
}
