package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/Svarcf/sever_go/internal/graph/model"
	"github.com/Svarcf/sever_go/internal/models"
)

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, createRoleInput *model.CreateRoleInput) (*models.RoleDTO, error) {
	role := models.NewRole(
		createRoleInput.Name,
	)
	return r.RoleService.CreateRole(role)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*models.RoleDTO, error) {
	return r.RoleService.GetAllRoles()
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id uint) (*models.RoleDTO, error) {
	return r.RoleService.GetRoleByID(id)
}
