package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"fmt"

	"github.com/Svarcf/sever_go/internal/graph/model"
	"github.com/Svarcf/sever_go/internal/models"
)

// CreateStandardPart is the resolver for the createStandardPart field.
func (r *mutationResolver) CreateStandardPart(ctx context.Context, createStandardPartInput *model.CreateStandardPartInput) (*models.StandardPartDTO, error) {
	standardPart := models.NewStandardPart(
		createStandardPartInput.Code,
		createStandardPartInput.Name,
		1,
	)
	return r.StandardPartService.CreateStandardPart(standardPart)
}

// UpdateStandardPart is the resolver for the updateStandardPart field.
func (r *mutationResolver) UpdateStandardPart(ctx context.Context, updateStandardPartInput *model.UpdateStandardPartInput) (*models.StandardPartDTO, error) {
	panic(fmt.Errorf("not implemented: UpdateStandardPart - updateStandardPart"))
}

// StandardParts is the resolver for the standardParts field.
func (r *queryResolver) StandardParts(ctx context.Context) ([]*models.StandardPartDTO, error) {
	return r.StandardPartService.GetStandardParts()
}

// StandardPart is the resolver for the standardPart field.
func (r *queryResolver) StandardPart(ctx context.Context, id uint) (*models.StandardPartDTO, error) {
	return r.StandardPartService.GetStandardPartById(id)
}
