package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"fmt"

	"github.com/Svarcf/sever_go/internal/graph/model"
	"github.com/Svarcf/sever_go/internal/models"
)

// CreateTool is the resolver for the createTool field.
func (r *mutationResolver) CreateTool(ctx context.Context, createToolInput *model.CreateToolInput) (*models.Tool, error) {
	panic(fmt.Errorf("not implemented: CreateTool - createTool"))
}

// Tools is the resolver for the tools field.
func (r *queryResolver) Tools(ctx context.Context) ([]*models.Tool, error) {
	panic(fmt.Errorf("not implemented: Tools - tools"))
}

// Tool is the resolver for the tool field.
func (r *queryResolver) Tool(ctx context.Context, code string) (*models.Tool, error) {
	panic(fmt.Errorf("not implemented: Tool - tool"))
}

// CreationDate is the resolver for the creationDate field.
func (r *toolResolver) CreationDate(ctx context.Context, obj *models.Tool) (*string, error) {
	panic(fmt.Errorf("not implemented: CreationDate - creationDate"))
}

// Dimensions is the resolver for the dimensions field.
func (r *toolResolver) Dimensions(ctx context.Context, obj *models.Tool) (*string, error) {
	panic(fmt.Errorf("not implemented: Dimensions - dimensions"))
}

// Tool returns ToolResolver implementation.
func (r *Resolver) Tool() ToolResolver { return &toolResolver{r} }

type toolResolver struct{ *Resolver }
